name: Spark Job Unit Test
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./pyspark
    steps:
      #Confira o código
      - uses: actions/checkout@v3
      #Instale o Python 3.7.10 (a versão que o EMR Serverless usa)
      - name: Set up Python 3.7.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.10
          cache: "pip"
          cache-dependency-path: "**/requirements-dev.txt"
      #Instale nossa pytest dependência de requirements-dev.txt
      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt
      #Roda o pytest
      - name: Analysing the code with pytest
        run: |
          python3 -m pytest
